name: CI

on:
  push:
    branches: [ main ]

jobs:
  build-appimage:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: install build dependencies
        run: |
            sudo apt-get update
            sudo apt-get install -y python3-pip python3-setuptools patchelf desktop-file-utils libgdk-pixbuf2.0-dev fakeroot strace fuse gpg squashfs-tools
            sudo pip3 install git+https://github.com/AppImageCrafters/appimage-builder.git@feat/type_3_format
      - name: build AppImage
        run: |
            appimage-builder --skip-test
      - uses: actions/upload-artifact@v2
        with:
          name: AppImage
          path: './*.AppImage*'
  publish:
    runs-on: ubuntu-20.04
    needs: build-appimage
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download AppImage from build job
        uses: actions/download-artifact@v2
        with:
          name: AppImage
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          automatic_release_tag: Continuous
          files: './*.AppImage*'