name: CI

on:
  push:
    branches: [ main ]

jobs:
  build-appimage:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: install build dependencies
        run: |
            sudo apt-get update
            sudo apt-get install -y python3-pip python3-setuptools patchelf desktop-file-utils libgdk-pixbuf2.0-dev fakeroot strace fuse gpg squashfs-tools
            sudo pip3 install git+https://github.com/AppImageCrafters/appimage-builder.git@feat/type_3_format
      - name: build AppImage
        run: |
            appimage-builder --skip-test
      - uses: actions/upload-artifact@v2
        with:
          name: AppImage
          path: './*.AppImage*'